spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soa_lab?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
  #  hibernate
  jpa:
    hibernate:
      ddl-auto: update
    # 打印SQL语句
    show-sql: true

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true